# Generated by Django 5.1 on 2024-10-25 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da cidade')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da conta')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
            },
        ),
    ]
