# Generated by Django 4.2.10 on 2024-10-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0003_alter_conta_cidade_movimentacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacoes',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
