# Generated by Django 4.2.10 on 2024-10-29 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('apelido', models.CharField(max_length=30, verbose_name='apelido')),
                ('primeiro_nome', models.CharField(max_length=30, verbose_name='primeiro nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-mail')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('is_trusty', models.BooleanField(default=False, verbose_name='trusty')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
        ),
    ]
